language: go
sudo: required

go:
  - 1.10.x
  - stable
  - master

matrix:
  # Failing on the development version of Go isn't too bad.
  allow_failures:
    - go: master

before_script:
  # Don't record coverage for protobuf/gen & replay/nondefault
  - cover_packages=$(go list ./... | grep -v "protobuf/gen\|replay/nondefault" | awk -vORS=',' '{ print $1 }' | sed 's/,$/\n/')

script:
  - go test -coverprofile=coverage.txt -coverpkg=$cover_packages ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0a4814dca40d4a21a37
    on_success: change
    on_failure: always
